name: Playwright Tests

on:
  pull_request:
    branches: [ develop, main ]

  push:
    branches: [ develop, main ]

  schedule:
    - cron: '0 2 * * *'

jobs:

  smoke:
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
        env: [staging]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - run: npm ci
      - run: npx playwright install --with-deps

      - name: Run Smoke Tests
        run: |
          TEST_ENV=${{ matrix.env }} \
          npx playwright test --project=${{ matrix.browser }} --grep @smoke

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: smoke-${{ matrix.browser }}
          path: playwright-report/


  regression:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
        env: [staging, prod]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - run: npm ci
      - run: npx playwright install --with-deps

      - name: Run Regression Tests
        run: |
          TEST_ENV=${{ matrix.env }} \
          npx playwright test --project=${{ matrix.browser }} --grep @regression

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: regression-${{ matrix.browser }}-${{ matrix.env }}
          path: playwright-report/


  full-suite:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
        env: [staging, prod]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - run: npm ci
      - run: npx playwright install --with-deps

      - name: Run Full Suite
        run: |
          TEST_ENV=${{ matrix.env }} \
          npx playwright test --project=${{ matrix.browser }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: full-${{ matrix.browser }}-${{ matrix.env }}
          path: playwright-report/
